### ISSUE TITLE
Não está funcionando no momento

### ISSUE THREAD

**Issue by jonasyonah** [YimMenu-Lua/YimActions#1]
Acho que o arquivo anime estar com problema uma vez que só o Samurai está sendo carregado E não está abrindo jeito nenhum

**Comment by jonasyonah** [comment]
![Captura de Tela (44)](https://github.com/YimMenu-Lua/YimActions/assets/166405815/01b1a570-40cc-4301-860e-276f95c0684e)

**Comment by jonasyonah** [comment]
![Captura de Tela (44)](https://github.com/YimMenu-Lua/YimActions/assets/166405815/57b18a89-e5a2-4a0e-ab31-df9d7d64ec4d)

**Comment by xesdoog** [comment]
Did you by any chance modify something in any of the Lua files? Like trying to translate the script or something?

Try downloading the script again and removing the config file **YimActions.cfg** located under:

######
    %AppData%\YimMenu\scripts_config

**Comment by xesdoog** [comment]
closing as unclear.
